# Version scheme
version: "3.8"

services:
  item-db: # Service db
    image: mongo:3 # Mongo db image
    volumes: # Volume target
      - app-db:/data/db 
    ports: # Mongo db port
      - 27017:27017
  item-app: # Service app
    image: ghcr.io/akhmaliswara/a433-microservices/item-app:v1 # Use image from github packages
    container_name: item-app # Container name
    ports: # Port mapping to 80
      - 80:8080
    restart: on-failure # Restart if stopped

# Volume     
volumes:
  app-db: